# Generated by Django 4.1.7 on 2023-10-08 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Theuser_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.TextField(max_length=70)),
            ],
        ),
        migrations.AlterField(
            model_name='theuser',
            name='name',
            field=models.TextField(max_length=70, unique=True),
        ),
        migrations.CreateModel(
            name='Theuser_worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(null=True)),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.theuser_skills')),
                ('theuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.theuser')),
            ],
        ),
        migrations.CreateModel(
            name='Theuser_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('websitelink', models.URLField(null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.theuser')),
            ],
        ),
        migrations.CreateModel(
            name='Job_listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=70)),
                ('description', models.TextField()),
                ('salary', models.IntegerField(max_length=10)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.job_category')),
            ],
        ),
    ]
