# Generated by Django 4.1.7 on 2023-10-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_job_category_theuser_skills_alter_theuser_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theuser',
            name='is_worker',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='theuser',
            name='password',
            field=models.TextField(max_length=254),
        ),
        migrations.AlterField(
            model_name='theuser',
            name='username',
            field=models.TextField(max_length=70, null=True),
        ),
    ]
