# Generated by Django 4.1.7 on 2023-10-08 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_theuser_is_worker_alter_theuser_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_listing',
            name='posted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.theuser'),
            preserve_default=False,
        ),
    ]
