# Generated by Django 4.1.7 on 2023-10-09 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_job_listing_edited_alter_job_listing_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theuser_conversation',
            fields=[
                ('conversation_identifier', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='theuser_messages',
            name='message_identifier',
        ),
        migrations.AddField(
            model_name='theuser_messages',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theuser_messages',
            name='message_body_isempty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='theuser_messages',
            name='message_body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='theuser_messages',
            name='message_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver', to='base.theuser'),
        ),
        migrations.AlterField(
            model_name='theuser_messages',
            name='message_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to='base.theuser'),
        ),
        migrations.CreateModel(
            name='Theuser_notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_header', models.TextField(max_length=256)),
                ('notification_body', models.TextField(max_length=256)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('notification_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifreceiver', to='base.theuser')),
                ('notification_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifsender', to='base.theuser')),
            ],
        ),
        migrations.AddField(
            model_name='theuser_messages',
            name='message_belongto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.theuser_conversation'),
            preserve_default=False,
        ),
    ]
