# Generated by Django 4.1.7 on 2023-10-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_theuser_conversation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theuser_notifications_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_types', models.TextField(max_length=256)),
            ],
        ),
    ]
