# Generated by Django 4.1.7 on 2023-10-09 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_theuser_notifications_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='theuser_notifications',
            name='isread',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theuser_notifications',
            name='post_linked',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.job_listing'),
            preserve_default=False,
        ),
    ]
