# Generated by Django 4.1.7 on 2023-10-09 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_theuser_notifications_isread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_listing',
            name='offered',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Job_pending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('Job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.job_listing')),
                ('pending_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.theuser')),
            ],
        ),
        migrations.CreateModel(
            name='Job_accepted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('Job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.job_listing')),
                ('accepted_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.theuser')),
            ],
        ),
    ]
