# Generated by Django 4.2.6 on 2023-10-17 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_job_listing_edited_remove_job_listing_offered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_listing',
            name='category',
        ),
    ]
