# Generated by Django 4.2.6 on 2023-10-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_job_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_listing',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job_listing',
            name='offered',
            field=models.BooleanField(default=False),
        ),
    ]
