# Generated by Django 4.2.6 on 2023-10-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_job_listing_edited_job_listing_offered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokengenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('csrf_token', models.TextField()),
            ],
        ),
    ]
