# Generated by Django 4.2.6 on 2023-10-17 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_tokengenerator'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_listing',
            name='posted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
