# Generated by Django 4.2.6 on 2023-10-17 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_job_listing_posted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_listing',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.job_category'),
        ),
    ]
