# Generated by Django 4.2.6 on 2023-10-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_job_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_category',
            name='category_name',
            field=models.TextField(max_length=70, null=True),
        ),
    ]
