# Generated by Django 4.2.6 on 2023-10-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_job_listing_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tokengenerator',
        ),
    ]
