# Generated by Django 4.2.6 on 2023-10-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_delete_tokengenerator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token_generator',
            fields=[
                ('token_rand', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
    ]
