# Generated by Django 4.2.6 on 2023-10-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_tokenhandlin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenhandlin',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tokenhandlin',
            name='token_gene',
        ),
        migrations.AddField(
            model_name='tokenhandlin',
            name='token_rand',
            field=models.TextField(default=11, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Token_generator',
        ),
    ]
