# Generated by Django 4.2.6 on 2023-11-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_tokenhandlin_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theuser',
            name='resume',
            field=models.FileField(null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='theuser_worker',
            name='location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theuser_worker',
            name='websitelink',
            field=models.URLField(null=True),
        ),
    ]
