# Generated by Django 4.2.6 on 2023-11-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_theuser_resume_theuser_worker_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theuser',
            name='resume',
        ),
        migrations.AddField(
            model_name='theuser_worker',
            name='resume',
            field=models.FileField(null=True, upload_to='resumes/'),
        ),
    ]
