# Generated by Django 4.2.6 on 2023-11-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_theuser_company_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theuser_worker',
            name='skills',
        ),
    ]
